// error status codes
const {
  BAD_REQUEST = 400, UNAUTHORIZED = 401, FORBIDDEN = 403,
  NOT_FOUND = 404, CONFLICT = 409, INTERNAL_SERVER_ERROR = 500,
} = process.env;

module.exports = {
  BAD_REQUEST, UNAUTHORIZED, FORBIDDEN, NOT_FOUND, CONFLICT, INTERNAL_SERVER_ERROR,
};
